
package inventorysystem;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Admin
 */
public class LoginForm extends javax.swing.JFrame {

    int mousepX;
    int mousepY;
    GlobalVariables cnn = new GlobalVariables();
    //GlobalVariables

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        Seticon();
        jtusername.requestFocus();
        this.icon1.setVisible(false);
        this.setLocationRelativeTo(null);
        showDate();
        showTime();
        active();

    }

    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        date.setText(s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                time.setText(s.format(d));
            }

        }
        ).start();
    }
    
    public void active(){
        try {
            if (!cnn.conn.isClosed()) {
                activeornot.setText("Connected");
                
            }
                
            } catch (Exception e) {

                activeornot1.setText("Disconnected");
}
    }

    public void close() {

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    public void login() {

        //To verify if the text field username and password is empty or not
        if (jtusername.getText().trim().isEmpty() & jtpassword.getText().trim().isEmpty()) {
            jlusernameerror.setText("Username is Empty");
            jlpassworderror.setText("Password is Empty");
        } else if (jtusername.getText().trim().isEmpty()) {
            jlusernameerror.setText("Username is Empty");
        } else if (jtpassword.getText().trim().isEmpty()) {
            jlpassworderror.setText("Password is Empty");
        } else {
            //end verifiying

            try {

                if (!cnn.conn.isClosed()) {
//         Class.forName("com.mysql.jdbc.Driver");
//         Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/inventorysystem","root","pardorla1234");
                    String sql = "SELECT * FROM users where Username=? and Userpassword=?";

                    cnn.ps = cnn.conn.prepareStatement(sql);
                    cnn.ps.setString(1, jtusername.getText());
                    cnn.ps.setString(2, jtpassword.getText());

                    cnn.rs = cnn.ps.executeQuery();

                    if (cnn.rs.next()) {

                        cnn.userid = cnn.rs.getString("UserId");
                        cnn.username = cnn.rs.getString("Username");
                        cnn.isAdmin = cnn.rs.getBoolean("isAdmin");

                        JOptionPane.showMessageDialog(null, "Welcome " + cnn.username + "  UserId:" + cnn.userid + "");

                        close();

                        new MainWindow().setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(null, "Access denied");
                        jtusername.setText("");
                        jtpassword.setText("");
                        jtusername.requestFocus();
                    }
                }
            } catch (Exception e) {

                JOptionPane.showMessageDialog(rootPane, "Connection Error", "CALL YOUR ADMINISTRATOR", JOptionPane.ERROR_MESSAGE);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        jtpassword = new javax.swing.JPasswordField();
        jtusername = new javax.swing.JTextField();
        jlpassworderror = new javax.swing.JLabel();
        jlusernameerror = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbexit = new javax.swing.JButton();
        jblogin = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        date = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        activeornot = new javax.swing.JLabel();
        activeornot1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("System Login");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("__");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Username:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/show_hide_password-07-512.png"))); // NOI18N
        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon1MousePressed(evt);
            }
        });
        jPanel1.add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 50, 30));

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/show_hide_password-08-512.png"))); // NOI18N
        icon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon2MousePressed(evt);
            }
        });
        jPanel1.add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 50, 30));

        jtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtpasswordActionPerformed(evt);
            }
        });
        jtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtpasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtpasswordKeyReleased(evt);
            }
        });
        jPanel1.add(jtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 220, 30));

        jtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtusernameActionPerformed(evt);
            }
        });
        jtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtusernameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtusernameKeyReleased(evt);
            }
        });
        jPanel1.add(jtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 220, 30));

        jlpassworderror.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlpassworderror.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(jlpassworderror, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 220, 20));

        jlusernameerror.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlusernameerror.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(jlusernameerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 220, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Password:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, -1, 30));

        jbexit.setBackground(new java.awt.Color(204, 0, 0));
        jbexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbexit.setText("EXIT");
        jbexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexitActionPerformed(evt);
            }
        });
        jbexit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbexitKeyPressed(evt);
            }
        });
        jPanel1.add(jbexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jblogin.setBackground(new java.awt.Color(0, 102, 0));
        jblogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jblogin.setText("LOGIN");
        jblogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbloginActionPerformed(evt);
            }
        });
        jblogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbloginKeyPressed(evt);
            }
        });
        jPanel1.add(jblogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 360, 190));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 360, 190));

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 120, 20));

        date1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date1.setText("Time:");
        jPanel3.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 50, 20));

        date2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date2.setText("Date:");
        jPanel3.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 50, 20));

        time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 110, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Status:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, 20));

        activeornot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        activeornot.setForeground(new java.awt.Color(51, 102, 0));
        jPanel3.add(activeornot, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 110, 20));

        activeornot1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        activeornot1.setForeground(new java.awt.Color(204, 0, 0));
        jPanel3.add(activeornot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 110, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/login.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 440));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int coordinateX = evt.getXOnScreen();
        int coordinateY = evt.getYOnScreen();
        this.setLocation(coordinateX - mousepX, coordinateY - mousepY);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jbloginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbloginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        } // TODO add your handling code here:
    }//GEN-LAST:event_jbloginKeyPressed

    private void jbloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbloginActionPerformed
        login();        // TODO add your handling code here:
    }//GEN-LAST:event_jbloginActionPerformed

    private void jbexitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbexitKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            close();
        } // TODO add your handling code here:
    }//GEN-LAST:event_jbexitKeyPressed

    private void jbexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexitActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jbexitActionPerformed

    private void jtusernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtusernameKeyReleased
        jlusernameerror.setText("");  // TODO add your handling code here:
    }//GEN-LAST:event_jtusernameKeyReleased

    private void jtusernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtusernameKeyPressed
        jtusername.setTransferHandler(null);
        String user = jtusername.getText();
        int length = user.length();
        if (length < 15) {
            jtusername.setEditable(true);
        } else {

            jtusername.setEditable(false);
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {

            jtusername.setEditable(true);
        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtpassword.requestFocus();
        }
    }//GEN-LAST:event_jtusernameKeyPressed

    private void jtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtusernameActionPerformed

    private void jtpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpasswordKeyReleased
        jlpassworderror.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jtpasswordKeyReleased

    private void jtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpasswordKeyPressed
        jtpassword.setTransferHandler(null);
        String pass = jtpassword.getText();
        int length = pass.length();
        if (length < 15) {
            jtpassword.setEditable(true);
        } else {

            jtpassword.setEditable(false);
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {

            jtpassword.setEditable(true);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        } // TODO add your handling code here:
    }//GEN-LAST:event_jtpasswordKeyPressed

    private void icon2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon2MousePressed
        icon2.setVisible(false);
        icon1.setVisible(true);
        jtpassword.setEchoChar((char) 0);// TODO add your handling code here:
    }//GEN-LAST:event_icon2MousePressed

    private void icon1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MousePressed
        icon1.setVisible(false);
        icon2.setVisible(true);
        jtpassword.setEchoChar('*');
        // TODO add your handling code here:
    }//GEN-LAST:event_icon1MousePressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.setState(LoginForm.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtpasswordActionPerformed
    private void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activeornot;
    private javax.swing.JLabel activeornot1;
    private javax.swing.JLabel date;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbexit;
    private javax.swing.JButton jblogin;
    private javax.swing.JLabel jlpassworderror;
    private javax.swing.JLabel jlusernameerror;
    private javax.swing.JPasswordField jtpassword;
    private javax.swing.JTextField jtusername;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
