/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Registration extends javax.swing.JFrame {

    int mousepX;
    int mousepY;
    GlobalVariables cnn = new GlobalVariables();

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        Seticon();
        this.setLocationRelativeTo(null);
        jtfemid.requestFocus(true);

    }

    public void close() {

        WindowEvent close = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(close);
    }

    public void register() {

        try {
            String pass = jpfpass.getText();
            String repass = jpfrepass.getText();

            if (pass.equals(repass)) {
                     if (!cnn.conn.isClosed()) {
                String sql = "SELECT * FROM employees where EmployeeId=?";
                cnn.ps = cnn.conn.prepareStatement(sql);
                cnn.ps.setString(1, jtfemid.getText());
                cnn.rs = cnn.ps.executeQuery();
                if (cnn.rs.next()) {
                    
                    close();

                } else {
                    JOptionPane.showMessageDialog(null, "Invalid EmployeeId");
                    jtfemid.setText("");
                    jtfemid.requestFocus();
                    return;
                }
                Statement stmt = (Statement) cnn.conn.createStatement();
                int UserId = 0;
                int isAdmin;
                int EmployeeId = Integer.parseInt(jtfemid.getText());
                String Username = jtfuser.getText();
                String Userpassword = jpfrepass.getText();
                if (chIsAdmin.isSelected()) {

                    isAdmin = 1;

                } else {

                    isAdmin = 0;

                }

                String sql1 = "INSERT INTO users VALUES('" + UserId + "','" + EmployeeId + "','" + Username + "','" + Userpassword + "','" + isAdmin + "');";
                stmt.executeUpdate(sql1);
                jtfemid.setText(null);
                jtfuser.setText(null);
                jpfpass.setText(null);
                jpfrepass.setText(null);

                JOptionPane.showMessageDialog(rootPane, "Successfully Added Account to Database:", "Successfully Added", JOptionPane.WARNING_MESSAGE);
            } 
            } else {
                jlerrorpass1.setText("Password don't match");
            }
            
        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, "Connection Error", "CALL YOUR ADMINISTRATOR", JOptionPane.ERROR_MESSAGE);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfemid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfuser = new javax.swing.JTextField();
        jpfpass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jpfrepass = new javax.swing.JPasswordField();
        chIsAdmin = new javax.swing.JCheckBox();
        jlerroruser = new javax.swing.JLabel();
        jlerrorid = new javax.swing.JLabel();
        jlerrorpass = new javax.swing.JLabel();
        jlerrorpass1 = new javax.swing.JLabel();
        jbclose = new javax.swing.JButton();
        jccreateacct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("__");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, 30));

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("System Registration");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Password:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 100, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("EmployeeID Validation:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 30));

        jtfemid.setBackground(new java.awt.Color(204, 204, 204));
        jtfemid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfemid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfemidActionPerformed(evt);
            }
        });
        jtfemid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfemidKeyPressed(evt);
            }
        });
        jPanel2.add(jtfemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 90, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Username:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 100, 30));

        jtfuser.setBackground(new java.awt.Color(204, 204, 204));
        jtfuser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfuserActionPerformed(evt);
            }
        });
        jtfuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfuserKeyPressed(evt);
            }
        });
        jPanel2.add(jtfuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 250, 30));

        jpfpass.setBackground(new java.awt.Color(204, 204, 204));
        jpfpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpfpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfpassActionPerformed(evt);
            }
        });
        jpfpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpfpassKeyPressed(evt);
            }
        });
        jPanel2.add(jpfpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 250, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Retype password:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, 30));

        jpfrepass.setBackground(new java.awt.Color(204, 204, 204));
        jpfrepass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpfrepass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpfrepassKeyPressed(evt);
            }
        });
        jPanel2.add(jpfrepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 250, 30));

        chIsAdmin.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        chIsAdmin.setText("Admin");
        chIsAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chIsAdminActionPerformed(evt);
            }
        });
        jPanel2.add(chIsAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        jlerroruser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlerroruser.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(jlerroruser, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 150, 30));

        jlerrorid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlerrorid.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(jlerrorid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 150, 30));

        jlerrorpass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlerrorpass.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(jlerrorpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 150, 30));

        jlerrorpass1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlerrorpass1.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(jlerrorpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 150, 30));

        jbclose.setBackground(new java.awt.Color(204, 0, 0));
        jbclose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbclose.setText("Exit");
        jbclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcloseActionPerformed(evt);
            }
        });
        jPanel2.add(jbclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, 40));

        jccreateacct.setBackground(new java.awt.Color(0, 153, 0));
        jccreateacct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jccreateacct.setText("Verify and Create Account");
        jccreateacct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jccreateacctActionPerformed(evt);
            }
        });
        jccreateacct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jccreateacctKeyPressed(evt);
            }
        });
        jPanel2.add(jccreateacct, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 620, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfuserActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        this.setState(Registration.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jbcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcloseActionPerformed

        new MainWindow().setVisible(true);
        close();
// TODO add your handling code here:
    }//GEN-LAST:event_jbcloseActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();// TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int coordinateX = evt.getXOnScreen();
        int coordinateY = evt.getYOnScreen();
        this.setLocation(coordinateX - mousepX, coordinateY - mousepY);     // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jtfemidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfemidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfemidActionPerformed

    private void jtfemidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfemidKeyPressed
        String employeeid = jtfemid.getText();
        int length = employeeid.length();

        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            if (length <= 4) {
                jtfemid.setEditable(true);
            } else {

                jtfemid.setEditable(false);
            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                jtfemid.setEditable(true);
            } else {
                jtfemid.setEditable(false);
            }

        }// TODO add your handling code here:
    }//GEN-LAST:event_jtfemidKeyPressed

    private void jtfuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfuserKeyPressed
        jtfuser.setTransferHandler(null);
        String user = jtfuser.getText();
        int length = user.length();

        if (length < 15) {
            jtfuser.setEditable(true);
        } else {
            jtfuser.setEditable(false);
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
            jtfuser.setEditable(true);

        }// TODO add your handling code here:
    }//GEN-LAST:event_jtfuserKeyPressed

    private void jpfpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfpassKeyPressed
        jpfpass.setTransferHandler(null);
        String pass = jpfpass.getText();
        int length = pass.length();
        if (length < 15) {
            jpfpass.setEditable(true);
        } else {
            jpfpass.setEditable(false);
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
            jlerrorpass.setText("");
            jpfpass.setEditable(true);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jpfpassKeyPressed

    private void jpfrepassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfrepassKeyPressed
        jpfrepass.setTransferHandler(null);
        String repass = jpfrepass.getText();
        int length = repass.length();
        if (length < 15) {
            jpfrepass.setEditable(true);
        } else {

            jpfrepass.setEditable(false);
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
            jlerrorpass1.setText("");
            jpfrepass.setEditable(true);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jpfrepassKeyPressed

    private void jccreateacctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jccreateacctActionPerformed

        register();

// TODO add your handling code here:
    }//GEN-LAST:event_jccreateacctActionPerformed

    private void jccreateacctKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jccreateacctKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            register();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jccreateacctKeyPressed

    private void chIsAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chIsAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chIsAdminActionPerformed

    private void jpfpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfpassActionPerformed
    private void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chIsAdmin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbclose;
    private javax.swing.JButton jccreateacct;
    private javax.swing.JLabel jlerrorid;
    private javax.swing.JLabel jlerrorpass;
    private javax.swing.JLabel jlerrorpass1;
    private javax.swing.JLabel jlerroruser;
    private javax.swing.JPasswordField jpfpass;
    private javax.swing.JPasswordField jpfrepass;
    private javax.swing.JTextField jtfemid;
    private javax.swing.JTextField jtfuser;
    // End of variables declaration//GEN-END:variables
}
