/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Joshua's
 */
public class UpdateProduct extends javax.swing.JFrame {

    int mousepX;
    int mousepY;
    GlobalVariables cnn = new GlobalVariables();

    //GlobalVariables
    /**
     * Creates new form UpdateProduct
     */
    public UpdateProduct() {
        initComponents();
        fillbrandcombobox();
        fillSpecificationcombobox();
        fillproducttypecombobox();
        fillPackagingTypecombobox();

    }

    public void close() {

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    public void updateproduct() {
        try {

            if (!cnn.conn.isClosed()) {
                String value1 = Productid.getText();
                String value2 = Productname.getText();
                String value3 = (String) Specification.getSelectedItem();
                String value4 = (String) Producttype.getSelectedItem();
                String value5 = (String) Productbrand.getSelectedItem();
                String value6 = (String) Packagingtype.getSelectedItem();
                String value7 = Quantityperpack.getText();
                String value8 = Description.getText();

                String sql = "update products set ProductName='" + value2 + "',ProductSpec='" + value3 + "',ProductType='" + value4 + "',ProductBrand='" + value5 + "',PackType='" + value6 + "',PackQuantity='" + value7 + "',ProductDescription='" + value8 + "'where ProductId='" + value1 + "'";

                cnn.ps = cnn.conn.prepareStatement(sql);
                cnn.ps.executeUpdate();
                Productid.setText(null);
                Productname.setText(null);
                Specification.setSelectedItem(null);
                Producttype.setSelectedItem(null);
                Productbrand.setSelectedItem(null);
                Packagingtype.setSelectedItem(null);
                Quantityperpack.setText(null);
                Description.setText(null);
                JOptionPane.showMessageDialog(null, "Updated");
                close();

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, "Connection Error", "CALL YOUR ADMINISTRATOR", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Productname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Specification = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Producttype = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Productbrand = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        Packagingtype = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        Quantityperpack = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Productid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Update Product");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        Productname.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Productname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 340, 30));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setText("Product Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setText("Specification:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        Specification.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.add(Specification, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 90, 30));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setText("Product Type:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        Producttype.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.add(Producttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 340, 30));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setText("Product Brand:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 30));

        Productbrand.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.add(Productbrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 340, 30));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel11.setText("Packaging Type:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 30));

        Packagingtype.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.add(Packagingtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 90, 30));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel12.setText("Quantity per package:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, 30));

        Quantityperpack.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Quantityperpack, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 70, 30));

        Description.setColumns(20);
        Description.setRows(5);
        jScrollPane1.setViewportView(Description);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 350, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel13.setText("Description:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 400, -1, -1));

        Update.setBackground(new java.awt.Color(0, 102, 0));
        Update.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel2.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        Productid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(Productid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 45, 23));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 540, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        updateproduct();
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        close();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int coordinateX = evt.getXOnScreen();
        int coordinateY = evt.getYOnScreen();
        this.setLocation(coordinateX - mousepX, coordinateY - mousepY);     // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged
    private void fillbrandcombobox() {
        try {

            if (!cnn.conn.isClosed()) {

                String sql = "select * from Brands";

                cnn.ps = cnn.conn.prepareStatement(sql);
                cnn.rs = cnn.ps.executeQuery();
                while (cnn.rs.next()) {
                    String brand = cnn.rs.getString("BrandName");
                    Productbrand.addItem(brand);

                }

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, "Connection Error", "CALL YOUR ADMINISTRATOR", JOptionPane.ERROR_MESSAGE);

        }
    }

    private void fillproducttypecombobox() {
        try {

            if (!cnn.conn.isClosed()) {

                String sql = "select * from ProductTypes";

                cnn.ps = cnn.conn.prepareStatement(sql);
                cnn.rs = cnn.ps.executeQuery();
                while (cnn.rs.next()) {
                    String brand = cnn.rs.getString("ProductTypeName");
                    Producttype.addItem(brand);

                }

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, "Connection Error", "CALL YOUR ADMINISTRATOR", JOptionPane.ERROR_MESSAGE);

        }
    }

    private void fillSpecificationcombobox() {
        try {

            if (!cnn.conn.isClosed()) {

                String sql = "select * from Specifications";

                cnn.ps = cnn.conn.prepareStatement(sql);
                cnn.rs = cnn.ps.executeQuery();
                while (cnn.rs.next()) {
                    String brand = cnn.rs.getString("SpecificationName");
                    Specification.addItem(brand);

                }

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, "Connection Error", "CALL YOUR ADMINISTRATOR", JOptionPane.ERROR_MESSAGE);

        }
    }

    private void fillPackagingTypecombobox() {
        try {

            if (!cnn.conn.isClosed()) {

                String sql = "select * from PackagingType";

                cnn.ps = cnn.conn.prepareStatement(sql);
                cnn.rs = cnn.ps.executeQuery();
                while (cnn.rs.next()) {
                    String brand = cnn.rs.getString("PackagingTypeName");
                    Packagingtype.addItem(brand);

                }

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, "Connection Error", "CALL YOUR ADMINISTRATOR", JOptionPane.ERROR_MESSAGE);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea Description;
    public javax.swing.JComboBox<String> Packagingtype;
    public javax.swing.JComboBox<String> Productbrand;
    public javax.swing.JLabel Productid;
    public javax.swing.JTextField Productname;
    public javax.swing.JComboBox<String> Producttype;
    public javax.swing.JTextField Quantityperpack;
    public javax.swing.JComboBox<String> Specification;
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
