/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Usedescription extends javax.swing.JFrame {
GlobalVariables cnn = new GlobalVariables();
GlobalVariables user = new GlobalVariables();
    /**
     * Creates new form Usedescription
     */
    public Usedescription() {
        initComponents();
        hideuser();
        hidepass();
        username.setFocusable(false);
        password.setFocusable(false);
        jLabel11.setText(String.valueOf(user.userid));
        userdescription();
    }
    
     public void userdescription(){
                try {
                    if (!cnn.conn.isClosed()) {
            String sql = "select * from users where UserId=?";
            cnn.ps = cnn.conn.prepareStatement(sql);
            cnn.ps.setString(1, jLabel11.getText());
            cnn.rs = cnn.ps.executeQuery();
           if (cnn.rs.next()) {
            jLabel12.setText(cnn.rs.getString(2));
            username.setText(cnn.rs.getString(3));
            password.setText(cnn.rs.getString(4));
            jLabel10.setText(cnn.rs.getString(5));
            
            }
                }
        } catch (Exception e) {
        }

    }    
    public void close() {

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    public void hideuser() {
        retypeusername.hide();
        relabel1.hide();
        cancel1.hide();
        username.setEditable(false);
    }

    public void hidepass() {
        retypepassword.hide();
        relabel.hide();
        cancel.hide();
        password.setEditable(false);
    }

    public void update() {
        String user = username.getText();
            String reuser = retypeusername.getText();

            if (user.equals(reuser)) {
                System.out.println("username match");
            }else{
                erroruser.setText("Username Don't match");
            }
            String pass = password.getText();
            String repass = retypepassword.getText();

            if (pass.equals(repass)) {
                System.out.println("password match");
            }else{
                errorpass.setText("Password Don't match");
            }
            
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        relabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        relabel1 = new javax.swing.JLabel();
        retypeusername = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        cancel1 = new javax.swing.JButton();
        errorpass = new javax.swing.JLabel();
        erroruser = new javax.swing.JLabel();
        retypepassword = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Account Description");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        relabel.setBackground(new java.awt.Color(0, 0, 0));
        relabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        relabel.setText("Retype new password:");
        jPanel2.add(relabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 30));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("UserId:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 30));

        jButton2.setBackground(new java.awt.Color(0, 102, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Change");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, 30));

        jButton3.setBackground(new java.awt.Color(0, 102, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Update Account");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 230, 30));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Account Username:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Description");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 80, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Account Password:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("EmployeeId:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 30));

        username.setBackground(new java.awt.Color(204, 204, 204));
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameKeyPressed(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 230, 30));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Account Description:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 230, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 230, 30));

        relabel1.setBackground(new java.awt.Color(0, 0, 0));
        relabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        relabel1.setText("Retype new Username:");
        jPanel2.add(relabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 30));

        retypeusername.setBackground(new java.awt.Color(204, 204, 204));
        retypeusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                retypeusernameKeyPressed(evt);
            }
        });
        jPanel2.add(retypeusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 230, 30));

        jButton4.setBackground(new java.awt.Color(153, 0, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        cancel.setBackground(new java.awt.Color(204, 0, 0));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancel.setText("cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel2.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 80, 30));

        cancel1.setBackground(new java.awt.Color(204, 0, 0));
        cancel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancel1.setText("cancel");
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });
        jPanel2.add(cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 80, 30));

        errorpass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        errorpass.setForeground(new java.awt.Color(153, 0, 0));
        jPanel2.add(errorpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 334, 230, 20));

        erroruser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        erroruser.setForeground(new java.awt.Color(153, 0, 0));
        jPanel2.add(erroruser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 230, 20));

        retypepassword.setBackground(new java.awt.Color(204, 204, 204));
        retypepassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        retypepassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                retypepasswordKeyPressed(evt);
            }
        });
        jPanel2.add(retypepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 230, 30));

        password.setBackground(new java.awt.Color(204, 204, 204));
        password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 230, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 520, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Do you want to continue action?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            password.setEditable(true);
            password.setFocusable(true);
            retypepassword.show();
            relabel.show();
            cancel.show();
        } else if (response == JOptionPane.NO_OPTION) {
            hidepass();
        } else if (response == JOptionPane.CLOSED_OPTION) {
            hidepass();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Do you want to continue action?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            username.setEditable(true);
            username.setFocusable(true);
            retypeusername.show();
            relabel1.show();
            cancel1.show();
        } else if (response == JOptionPane.NO_OPTION) {
            hideuser();
        } else if (response == JOptionPane.CLOSED_OPTION) {
            hideuser();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        hidepass();
        password.setFocusable(false);
        errorpass.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        hideuser();
        username.setFocusable(false);
        erroruser.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_cancel1ActionPerformed

    private void usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyPressed
        username.setTransferHandler(null);
        String user = username.getText();
        int length = user.length();
        if (length < 15) {
            username.setEditable(true);
        } else {
            username.setEditable(false);
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
            erroruser.setText("");
            username.setEditable(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_usernameKeyPressed

    private void retypeusernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_retypeusernameKeyPressed
        retypeusername.setTransferHandler(null);
        String reuser = retypeusername.getText();
        int length = reuser.length();
        if (length < 15) {
            retypeusername.setEditable(true);
        } else {

            retypeusername.setEditable(false);
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
            erroruser.setText("");
            retypeusername.setEditable(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_retypeusernameKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      update(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        password.setTransferHandler(null);
        String pass = password.getText();
        int length = pass.length();
        if (length < 15) {
            password.setEditable(true);
        } else {
            password.setEditable(false);
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
            errorpass.setText("");
            password.setEditable(true);
        }            // TODO add your handling code here:
    }//GEN-LAST:event_passwordKeyPressed

    private void retypepasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_retypepasswordKeyPressed
        retypepassword.setTransferHandler(null);
        String repass = retypepassword.getText();
        int length = repass.length();
        if (length < 15) {
            retypepassword.setEditable(true);
        } else {
            retypepassword.setEditable(false);
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
            errorpass.setText("");
            retypepassword.setEditable(true);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_retypepasswordKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        close();
        new MainWindow().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usedescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usedescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usedescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usedescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usedescription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton cancel1;
    private javax.swing.JLabel errorpass;
    private javax.swing.JLabel erroruser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel relabel;
    private javax.swing.JLabel relabel1;
    private javax.swing.JPasswordField retypepassword;
    private javax.swing.JTextField retypeusername;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
